apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  selector:
    matchLabels:
      app: hello-kubernetes
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-kubernetes
        version: {{ .Values.hellokubernetes.deployment.version }}
    spec:
      containers:
      - name: hello-kubernetes
        image: {{ .Values.hellokubernetes.deployment.image }}
        resources:
          limits:
            memory: 128M
            cpu: .1
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: hello-kubernetes
        - secretRef:
            name: hello-kubernetes
