apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
  annotations:
spec:
  type: NodePort
  selector:
    app: hello-kubernetes
  ports:
    - name: hello-kubernetes-port
      protocol: TCP
      port: 80
      targetPort: 80
