apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
  annotations:
spec:
  type: {{ .Values.hellokubernetes.service.type }}
  selector:
    app: hello-kubernetes
  ports:
    - name: hello-kubernetes-port
      protocol: TCP
      port: 80
      targetPort: 80
